[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "courtsumger"
version = "0.1.0"
description = "German Court Summarization Dataset"
readme = "README.md"
requires-python = ">=3.8"
authors = [{name = "Sebastian Nagl", email = "sebastian.nagl@tum.de"}]
license = {text = "MIT"}
dependencies = [
    "pandas>=1.3.0",
    "matplotlib>=3.4.0",
    "numpy>=1.20.0",
    "pathlib",
    "datasets>=3.4.0",
    "transformers>=4.49.0",
    "ipykernel>=6.0.0",
    "jupyter>=1.0.0",
    "seaborn>=0.11.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "black>=21.5b2",
    "isort>=5.9.0",
]

[tool.black]
line-length = 88
target-version = ["py38"]

[tool.isort]
profile = "black"
line_length = 88
